apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todo-app-backend
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: 5000
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
